apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reggeltbot-beta
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:gcb-build-id': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            'f:app.kubernetes.io/version': {}
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                'f:gcb-build-id': {}
              'f:labels':
                'f:app.kubernetes.io/version': {}
            'f:spec':
              'f:containers':
                'k:{"name":"reggeltbot-1"}':
                  'f:image': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2021-03-04T00:15:04Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"reggeltbot-1"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"APIURL"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"GOOGLE_APPLICATION_CREDENTIALS"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"PROD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"RAPIURL"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/var/secrets/google"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"google-cloud-key"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-03-04T00:19:42Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      time: '2021-03-04T00:19:43Z'
  name: reggeltbot-beta
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reggeltbot-beta
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reggeltbot-beta
    spec:
      containers:
        - env:
            - name: PROD
              valueFrom:
                configMapKeyRef:
                  key: PROD
                  name: reggeltbot-beta-config-7ea9
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_APPLICATION_CREDENTIALS
                  name: reggeltbot-beta-config-7ea9
            - name: RAPIURL
              valueFrom:
                configMapKeyRef:
                  key: RAPIURL
                  name: reggeltbot-beta-config-7ea9
            - name: APIURL
              valueFrom:
                configMapKeyRef:
                  key: APIURL
                  name: reggeltbot-beta-config-7ea9
          image: gcr.io/zal1000/github.com/zal1000/reggeltbot
          imagePullPolicy: IfNotPresent
          name: reggeltbot-1
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
      volumes:
        - name: google-cloud-key
          secret:
            defaultMode: 420
            secretName: firebase-key
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reggeltbot-beta
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
        'f:spec':
          'f:ports':
            .: {}
            'k:{"port":3000,"protocol":"TCP"}':
              .: {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app': {}
          'f:sessionAffinity': {}
          'f:type': {}
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-01-27T02:46:59Z'
  name: reggeltbot-beta-service
  namespace: default
spec:
  clusterIP: 10.8.6.142
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: reggeltbot-beta
  sessionAffinity: None
  type: ClusterIP
